name       : korla-icon-theme
version    : 1.2.6
release    : 11
source     :
    - https://github.com/bikass/korla/archive/v1.2.6.tar.gz : 0b080ce5a096cd24f830095137b20cc85b96ae9c8981c93f7e0403466be0878a
homepage   : https://github.com/bikass/korla
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Korla icon theme
description: |
    Korla icon theme is a mix of the following icon sets: Korla and Papirus.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r korla* $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*

    # Delete useless files
    rm -f $installdir/usr/share/icons/*/{create-new-icon-theme.cache.sh,icon-theme.cache}

    # Replacing menu icon
    install -Dm00644 $pkgfiles/start-here-symbolic.svg $installdir/usr/share/icons/korla/places/symbolic/start-here-symbolic.svg
