name       : korla-icon-theme
version    : 1.2.8
release    : 12
source     :
    - https://github.com/bikass/korla/archive/v1.2.8.tar.gz : 1081c72aa6675a15b5e6fa7f8991acc6e28a86f835d51ddd76169af3fb6b8f16
homepage   : https://github.com/bikass/korla
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Korla icon theme
description: |
    Korla icon theme is a mix of the following icon sets: Korla and Papirus.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r korla* $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*

    # Delete useless files
    rm -f $installdir/usr/share/icons/*/{create-new-icon-theme.cache.sh,icon-theme.cache}

    # Replacing menu icon
    install -Dm00644 $pkgfiles/start-here-symbolic.svg $installdir/usr/share/icons/korla/places/symbolic/start-here-symbolic.svg
