name       : korla-icon-theme
version    : 1.1.5
release    : 1
source     :
    - https://github.com/bikass/korla/archive/v1.1.5.tar.gz : 89fbfe7cc60174b2ff3a867b5ccdf5977c39780fd53267ef3f01f74cc73ff17a
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Korla icon theme
description: |
    Korla icon theme is a mix of the following icon sets: Korla and Papirus.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {korla,korla-light,korla-light-panel} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*
