name       : korla-icon-theme
version    : 1.4.1
release    : 18
source     :
    - https://github.com/bikass/kora/archive/v1.4.1.tar.gz : 07894acf50d6b6fe0f62f3fa9767117b816586c3a4b227c6c8ab911ff04c3c42
homepage   : https://github.com/bikass/kora
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Kora (formerly Korla) a SVG icon theme
description: |
    Kora (formerly Korla) is an SVG icon theme with lots of new icons for GNU/Linux operating systems.
setup      : |
    sed -i -e 's|Kora|Korla|g' */index.theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r kora $installdir/usr/share/icons/korla
    cp -r kora-light $installdir/usr/share/icons/korla-light
    cp -r kora-light-panel $installdir/usr/share/icons/korla-light-panel
    cp -r kora-pgrey $installdir/usr/share/icons/korla-pgrey
    chmod -R 00644 $installdir/usr/share/icons/*

    # Because name changed from korla to kora, need to fix all symbolik links
    pushd $installdir/usr/share/icons/korla
    for theme in korla-light korla-light-panel korla-pgrey; do
        cd ../${theme}
        for sl in animations apps categories devices emblems emotes mimetypes status; do
            rm -rf ${sl}
            ln -sv ../korla/${sl} ${sl}
        done
    done

    # fix other symbolik links
    cd ../korla-light
    rm panel && ln -sv ../korla/panel panel
    rm places && ln -sv ../korla/places places

    cd ../korla-light-panel
    rm actions && ln -sv ../korla/actions actions
    rm places && ln -sv ../korla/places places

    cd ../korla-pgrey
    rm actions && ln -sv ../korla/actions actions
    rm panel && ln -sv ../korla/panel panel
    rm places/symbolic && ln -sv ../../korla/places/symbolic places/symbolic
    popd

    # Delete useless files
    rm -f $installdir/usr/share/icons/*/{create-new-icon-theme.cache.sh,icon-theme.cache}

    # Replacing menu icon
    install -Dm00644 $pkgfiles/start-here-symbolic.svg $installdir/usr/share/icons/korla/places/symbolic/start-here-symbolic.svg
