name       : korla-icon-theme
version    : 1.3.0
release    : 14
source     :
    - https://github.com/bikass/korla/archive/v1.3.0.tar.gz : 91dd220bf2191c7fae159223de4f24a42d0549b1c49822006fa92a119267589b
homepage   : https://github.com/bikass/korla
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Korla icon theme
description: |
    Korla icon theme is a mix of the following icon sets: Korla and Papirus.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r korla* $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*

    # Delete useless files
    rm -f $installdir/usr/share/icons/*/{create-new-icon-theme.cache.sh,icon-theme.cache}

    # Replacing menu icon
    install -Dm00644 $pkgfiles/start-here-symbolic.svg $installdir/usr/share/icons/korla/places/symbolic/start-here-symbolic.svg
