name       : korla-icon-theme
version    : 1.2.1
release    : 5
source     :
    - https://github.com/bikass/korla/archive/v1.2.1.tar.gz : 1cb01ee6e5bf56680f9daab3ecd746ea06fa2b2f1145f0a923b50f5f0f174189
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Korla icon theme
description: |
    Korla icon theme is a mix of the following icon sets: Korla and Papirus.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r {korla,korla-light,korla-light-panel} $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*

    # Delete useless files
    rm -f $installdir/usr/share/icons/*/{create-new-icon-theme.cache.sh,icon-theme.cache}

    # Replacing menu icon
    install -Dm00644 $pkgfiles/start-here-symbolic.svg $installdir/usr/share/icons/korla/places/symbolic/start-here-symbolic.svg
