name       : korla-icon-theme
version    : 1.3.1
release    : 15
source     :
    - https://github.com/bikass/korla/archive/v1.3.1.tar.gz : c87fb21f377893c60532400bd747bed8efdacb8efd92ab79dee575b7c87fe896
homepage   : https://github.com/bikass/korla
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Korla icon theme
description: |
    Korla icon theme is a mix of the following icon sets: Korla and Papirus.
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r korla* $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*

    # Delete useless files
    rm -f $installdir/usr/share/icons/*/{create-new-icon-theme.cache.sh,icon-theme.cache}

    # Replacing menu icon
    install -Dm00644 $pkgfiles/start-here-symbolic.svg $installdir/usr/share/icons/korla/places/symbolic/start-here-symbolic.svg
