name       : korla-icon-theme
version    : 1.5.0
release    : 26
source     :
    - https://github.com/bikass/kora/archive/refs/tags/v1.5.0.tar.gz : 2001e296b8ec860f1b03f3bbbf3867aaa0dd471e624d7832f9fc266266bdde59
homepage   : https://github.com/bikass/kora
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Kora (formerly Korla) a SVG icon theme
description: |
    Kora (formerly Korla) is an SVG icon theme with lots of new icons for GNU/Linux operating systems.
setup      : |
    sed -i -e 's|Kora|Korla|g' */index.theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r kora $installdir/usr/share/icons/korla
    cp -r kora-light $installdir/usr/share/icons/korla-light
    cp -r kora-light-panel $installdir/usr/share/icons/korla-light-panel
    cp -r kora-pgrey $installdir/usr/share/icons/korla-pgrey
    chmod -R 00644 $installdir/usr/share/icons/*

    # Because name changed from korla to kora, need to fix all symbolic links
    pushd $installdir/usr/share/icons/korla
    for theme in korla-light korla-light-panel korla-pgrey; do
        cd ../${theme}
        for sl in animations apps categories devices emblems emotes mimetypes status; do
            rm -rf ${sl}
            ln -sv ../korla/${sl} ${sl}
        done
    done

    # Fix other symbolic links
    cd ../korla-light
    rm panel && ln -sv ../korla/panel panel
    rm places && ln -sv ../korla/places places

    cd ../korla-light-panel
    rm actions && ln -sv ../korla/actions actions
    rm places && ln -sv ../korla/places places

    cd ../korla-pgrey
    rm actions && ln -sv ../korla/actions actions
    rm panel && ln -sv ../korla/panel panel
    rm places/symbolic && ln -sv ../../korla/places/symbolic places/symbolic
    popd

    # Delete useless files
    rm -f $installdir/usr/share/icons/*/{create-new-icon-theme.cache.sh,icon-theme.cache}

    # Replace menu icon
    install -Dm00644 $pkgfiles/start-here-symbolic.svg $installdir/usr/share/icons/korla/places/symbolic/start-here-symbolic.svg

    # Clean some unnecessary icons
    rm $installdir/usr/share/icons/korla/apps/scalable/*elementary*
